### ISSUE TITLE
Add Tab completion to position system

### ISSUE THREAD

**Issue by marylieh** [marylieh/SimpleWarpV3#10]
Add the tab completion that has been added to the warp system to the position system.

**Comment by Utlamo** [comment]
Ok i do it tomorrow. Add to /delwarp too? I think if without is beter for secure. Miss click delete.

**Comment by marylieh** [comment]
I'm with you that this could be dangerous so leave /delwarp out :)

**Comment by Utlamo** [comment]
check this out pull request

**Comment by Utlamo** [comment]
hello im slowly back to alive, close this old issue
