### ISSUE TITLE
Can't add permissions on aternos

### ISSUE THREAD

**Issue by Vastfoool** [marylieh/SimpleWarpV3#12]
I've been trying to add permissions for players that dont have OP on the server. I want then to use /warp and /warps but they can't since they dont have the permissions. I'm using aternos, and when i go on the simplewarp file theres only the warps.yml
I hope someone can help me, thank you :)

**Comment by marylieh** [comment]
Hi @Vastfoool,
what permission system do you use on your server to give the permissions to your players?
You can also add me on Discord if thats more likely to you :) marie <3#0031
