### ISSUE TITLE
Can't add separate permissions per teleport

### ISSUE THREAD

**Issue by obliviator123** [marylieh/SimpleWarpV3#13]
I would like to have certain warps for only certain ranks.

As far as I can see this isn't possible currently and would love for this to be implemented.

Perhaps something like

simplewarp.warp.{warpname}
simplewarp.warps.{warpname}

This would help out a lot Thanks :D

**Comment by marylieh** [comment]
Hi @obliviator123 
I added the feature that you suggested. Now you can enable it in your config: "RequirePermissionForEachWarp". You need ofc the newest Version. I suggest downloading it here from GitHub under "releases" or from CircleCI.
If you enabled the new feature in your config, every Warp Point gets an individual permission, that follows this scheme: simplewarp.warp.WARPNAME
You have to replace WARPNAME with the exact name of your Warp Point. If you give the correct permissions to your players, only the one with the permissions can see/use the warp points.

I hope this helps :))
