### ISSUE TITLE
Permission setting keeps reverting. (Urgent 1.20 issue?)

### ISSUE THREAD

**Issue by obliviator123** [marylieh/SimpleWarpV3#14]
Hello,

When using the plugin recently I noticed players could warp to any warp despite them not having permission to do so.

I checked the config and sure enough:
**RequirePermissionForEachWarp: false**

So I tried setting it to true and yet when I logged back into the server players could still warp anywhere, so once again I checked the file and it had reverted to false. I triple checked however no matter what only that section of the config would revert to it's default settings including other toggleable options.

PositionSystem: false
auto-update: true
PlayerWarpsOnly: false
RequirePermissionForEachWarp: false

This was disastrous for my server as staff and paid users had their own warps and anyone could now use them which could have been a major security flaw if my players didn't notify me.

I am running a 1.20.1 server and I think that this may be the issue, I think the first step towards a fix would definitely be an update to 1.20.1 at the least :D

**Comment by marylieh** [comment]
Hi @obliviator123,
I'm sorry that you had to experience such a major security flaw. 
Please make sure that your server is stopped while you are editing the config file. A reload will not read the new configuration, instead, it will revert to the previous value. 
If you already did this step and the error is still there, please tell me which plugins and the exact version your server is running so I can try to replicate your problem.
Thank you for using the SimpleWarp plugin :)
