### ISSUE TITLE
Default Permission with Permission.yml

### ISSUE THREAD

**Issue by bakinazik** [marylieh/SimpleWarpV3#15]
Is it possible to use that way?

**Comment by marylieh** [comment]
I'm sorry if I don't understand your request correctly but if I do, this is currently not possible. 
If you want I can add this feature so you can set permissions for warp points in your permission.yml file which are applied by default for all players.

**Comment by YMLeeo** [comment]
I tried setting simplewarp.warp.WARPNAME in default.
Unable to use after testing.
If this function is not supported now, I hope it can be added.

**Comment by marylieh** [comment]
Version 3.8 of the plugin now features the requested feature :)
